kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: icp:develop
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
rules:
- apiGroups: ["icp.ibm.com"]
  resources: ["images"]
  verbs: ["create", "get", "list", "patch", "update", "watch"]
